import { Weapon } from '@/utils/weaponType'

export const pistols: Record<string, Weapon> = {
	/* deadeye: {
		name: 'Deadeye',
		category: 'pistol',
		damageType: 'physical',
		damageType2: '',
		damage: 51,
		damage2: 0,
		ammoType: '7.5MM',
		magCapacity: 6,
		fireRate: 12,
		range: 40,
		accuracy: 67.1,
		mass: 2.3,
		value: 5300,
		modSlots: [
			{
				slotType: 'barrel',
				mods: [
					//first mod slot should be the default mod
					{ name: 'Standard Barrel', description: 'standard issue barrel' },
					{
						name: 'Short Barrel',
						description:
							'increases aim down sight speed at the cost of accuaracy and recoil control',
					},
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'laser',
				mods: [
					{
						name: 'Laser Sight',
						description:
							'laser sight attachment to help with target acquisition and increase accuracy',
					},
					{ name: 'No Mod', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'optic',
				mods: [
					{ name: 'Iron Sights', description: 'standard issue iron sights' },
					{ name: 'Recon Scope', description: 'marks enemies while aiming' },
					{
						name: 'Reflex Sight',
						description:
							'reflex sight for quicker target acquistion and visibility',
					},
					{
						name: 'Short Scope',
						description: 'short scope for 2x magnified view',
					},
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'muzzle',
				mods: [
					{ name: 'No Mod', description: '' },
					{
						name: 'Compensator',
						description:
							'increases stability and hip-fire accuracy at the cost of long-range accuracy',
					},
					{
						name: 'Muzzle Brake',
						description:
							'increases long-range accuracy and stability at the cost of hip-fire accuracy',
					},
					{
						name: 'Suppressor',
						description:
							'vastly reduces acoustic intensity while increasing accuracy at the cost of range',
					},
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'grip and stock',
				mods: [
					{ name: 'Standard Grip', description: 'standard issue grip' },
					{
						name: 'Tactical Grip',
						description:
							'A lighter grip that increases aim down sight speed, reload speed, and stability',
					},
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'magazine and battery',
				mods: [
					{
						name: 'Penetrator Rounds',
						description:
							'incredibly powerful rounds that can pass through multiple enemies',
					},
					{
						name: 'Standard Whitehot Rounds',
						description:
							'standard chemically-tipped rounds that burn on contact',
					},
					{
						name: 'Armor-Piercing Rounds',
						description:
							'more powerful casing can penetrate even the sturdiest armors',
					},
					{
						name: 'Depleted Uranium Rounds',
						description:
							'built using depleted uranium, these rounds can penetrate any armor',
					},
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'internal',
				mods: [
					{ name: 'No Mod', description: '' },
					{
						name: 'Hair Trigger',
						description:
							'installs a lighter trigger pull for increase fire rate',
					},
					{ name: 'High Powered', description: 'increases damage done' },
					{
						name: 'High Velocity',
						description: 'internal module that increases accuracy and range',
					},
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'receiver',
				mods: [
					{
						name: 'Semi-automatic',
						description: 'receiver that fires once per trigger pull',
					},
					{
						name: 'Binary Trigger',
						description:
							'a binary trigger allows for the weapon to fire on pull and release of the trigger for a faster fire rate',
					},
				],
				defaultMod: 0,
				disabled: false,
			},
		],
	}, */
	eon: {
		name: 'Eon',
		category: 'pistol',
		damageType: 'physical',
		damageType2: '',
		damage: 12,
		damage2: 0,
		ammoType: '7.77MM',
		magCapacity: 12,
		fireRate: 50,
		range: 20,
		accuracy: 67.5,
		mass: 0.55,
		value: 750,
		picture: 'Eon.webp',
		modSlots: [
			{
				slotType: 'barrel',
				mods: [
					//first mod slot should be the default mod
				],
				defaultMod: 0,
				disabled: true,
			},
			{
				slotType: 'laser',
				mods: [],
				defaultMod: 0,
				disabled: true,
			},
			{
				slotType: 'optic',
				mods: [
					{ name: 'Glow Sights', description: '' },
					{
						name: 'Reflex Sight',
						description:
							'Reflex sight for quicker target acquistion and visibility',
					},
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'muzzle',
				mods: [
					{ name: 'No Mod', description: '' },
					{
						name: 'Compensator',
						description:
							'increases stability and hip-fire accuracy at the cost of long-range accuracy',
					},
					{
						name: 'Muzzle Brake',
						description:
							'increases long-range accuracy and stability at the cost of hip-fire accuracy',
					},
					{
						name: 'Suppressor',
						description:
							'vastly reduces acoustic intensity while increasing accuracy at the cost of range',
					},
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'grip and stock',
				mods: [],
				defaultMod: 0,
				disabled: true,
			},
			{
				slotType: 'magazine and battery',
				mods: [
					{ name: 'Standard Magazine', description: 'standard issue magazine' },
					{ name: 'Drum Magazine', description: '' },
					{ name: 'Explosive Rounds', description: '' },
					{ name: 'Large Magazine', description: '' },
					{ name: 'Tactical Magazine', description: '' },
					{ name: 'Whitehot Rounds', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'laser',
				mods: [
					{ name: 'No Mod', description: '' },
					{ name: 'Laser Sight', description: '' },
					{ name: 'Recon Laser Sight', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'internal',
				mods: [
					{ name: 'No Mod', description: '' },
					{ name: 'Hair Trigger', description: '' },
					{ name: 'High Velocity', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'receiver',
				mods: [
					{ name: 'Semi-automatic', description: '' },
					{ name: 'Binary Trigger', description: '' },
					{ name: 'Burst Fire', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
		],
	},
	kraken: {
		name: 'Kraken',
		category: 'pistol',
		damageType: 'physical',
		damageType2: '',
		damage: 3,
		damage2: 0,
		ammoType: '6.5MM',
		magCapacity: 25,
		fireRate: 150,
		range: 20,
		accuracy: 69.6,
		mass: 1,
		value: 748,
		picture: 'Kraken.webp',
		modSlots: [
			{
				slotType: 'barrel',
				mods: [
					//first mod slot should be the default mod
					{ name: 'Standard Barrel', description: '' },
					{ name: 'Bull Barrel', description: '' },
					{ name: 'Long Barrel', description: '' },
					{ name: 'Suppressor', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'laser',
				mods: [
					{ name: 'No Mod', description: '' },
					{ name: 'Laser Sight', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'optic',
				mods: [
					{ name: 'Iron Sights', description: '' },
					{ name: 'Reflex Sight', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'muzzle',
				mods: [
					{ name: 'Standard Muzzle', description: '' },
					{ name: 'Compensator', description: '' },
					{ name: 'Large Muzzle Brake', description: '' },
					{ name: 'Muzzle Brake', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'grip and stock',
				mods: [],
				defaultMod: 0,
				disabled: true,
			},
			{
				slotType: 'magazine and battery',
				mods: [
					{ name: 'Standard Magazine', description: '' },
					{ name: 'Drum Magazine', description: '' },
					{ name: 'Gut Buster Rounds', description: '' },
					{ name: 'Large Magazine', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'internal',
				mods: [
					{ name: 'No Mod', description: '' },
					{
						name: 'Hair Trigger',
						description:
							'installs a lighter trigger pull for increase fire rate',
					},
					{ name: 'High Powered', description: 'increases damage done' },
					{
						name: 'High Velocity',
						description: 'internal module that increases accuracy and range',
					},
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'receiver',
				mods: [],
				defaultMod: 0,
				disabled: true,
			},
		],
	},
	oldEarthPistol: {
		name: 'Old Earth Pistol',
		category: 'pistol',
		damageType: 'physical',
		damageType2: '',
		damage: 28,
		damage2: 0,
		ammoType: '.45 Caliber',
		magCapacity: 9,
		fireRate: 66.7,
		range: 20,
		accuracy: 66.9,
		mass: 1.1,
		value: 4350,
		picture: 'Old_Earth_Pistol.webp',
		modSlots: [
			{
				slotType: 'barrel',
				mods: [],
				defaultMod: 0,
				disabled: true,
			},
			{
				slotType: 'laser',
				mods: [],
				defaultMod: 0,
				disabled: true,
			},
			{
				slotType: 'muzzle',
				mods: [
					{ name: 'No Mod', description: '' },
					{ name: 'Compensator', description: '' },
					{ name: 'Short Suppressor', description: '' },
					{ name: 'Suppresor', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'optic',
				mods: [],
				defaultMod: 0,
				disabled: true,
			},
			{
				slotType: 'grip and stock',
				mods: [
					{ name: 'Standard Grip', description: '' },
					{ name: 'Tactical Grip', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'magazine and battery',
				mods: [
					{ name: 'Standard Magazine', description: '' },
					{ name: 'Armor-Piercing Rounds', description: '' },
					{ name: 'Large Magazine', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'internal',
				mods: [
					{ name: 'No Mod', description: '' },
					{
						name: 'Hair Trigger',
						description:
							'installs a lighter trigger pull for increase fire rate',
					},
					{ name: 'High Powered', description: 'increases damage done' },
					{
						name: 'High Velocity',
						description: 'internal module that increases accuracy and range',
					},
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'receiver',
				mods: [],
				defaultMod: 0,
				disabled: true,
			},
		],
	},
	rattler: {
		name: 'Rattler',
		category: 'pisols',
		damageType: 'physical',
		damageType2: '',
		damage: 10,
		damage2: 0,
		ammoType: '.27 Caliber',
		magCapacity: 12,
		fireRate: 50,
		range: 20,
		accuracy: 68.1,
		mass: 0.85,
		value: 942,
		picture: 'Rattler.webp',
		modSlots: [
			{
				slotType: 'barrel',
				mods: [
					//first mod slot should be the default mod
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'laser',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'optic',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'muzzle',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'grip and stock',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'magazine and battery',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'internal',
				mods: [
					{ name: 'No Mod', description: '' },
					{
						name: 'Hair Trigger',
						description:
							'installs a lighter trigger pull for increase fire rate',
					},
					{ name: 'High Powered', description: 'increases damage done' },
					{
						name: 'High Velocity',
						description: 'internal module that increases accuracy and range',
					},
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'receiver',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
		],
	},
	razorback: {
		name: 'Razorback',
		category: 'pistol',
		damageType: 'physical',
		damageType2: '',
		damage: 51,
		damage2: 0,
		ammoType: '7.5MM',
		magCapacity: 6,
		fireRate: 12,
		range: 40,
		accuracy: 67.1,
		mass: 2.3,
		value: 5300,
		picture: 'Razorback.webp',
		modSlots: [
			{
				slotType: 'barrel',
				mods: [
					//first mod slot should be the default mod
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'laser',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'optic',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'muzzle',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'grip and stock',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'magazine and battery',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'internal',
				mods: [
					{ name: 'No Mod', description: '' },
					{
						name: 'Hair Trigger',
						description:
							'installs a lighter trigger pull for increase fire rate',
					},
					{ name: 'High Powered', description: 'increases damage done' },
					{
						name: 'High Velocity',
						description: 'internal module that increases accuracy and range',
					},
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'receiver',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
		],
	},
	regulator: {
		name: 'Regulator',
		category: 'pistol',
		damageType: 'regulator',
		damageType2: '',
		damage: 48,
		damage2: 0,
		ammoType: '.43 Ultramag',
		magCapacity: 8,
		fireRate: 18,
		range: 20,
		accuracy: 71.3,
		mass: 0.7,
		value: 4450,
		picture: 'Regulator.webp',
		modSlots: [
			{
				slotType: 'barrel',
				mods: [
					//first mod slot should be the default mod
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'laser',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'optic',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'muzzle',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'grip and stock',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'magazine and battery',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'internal',
				mods: [
					{ name: 'No Mod', description: '' },
					{
						name: 'Hair Trigger',
						description:
							'installs a lighter trigger pull for increase fire rate',
					},
					{ name: 'High Powered', description: 'increases damage done' },
					{
						name: 'High Velocity',
						description: 'internal module that increases accuracy and range',
					},
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'receiver',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
		],
	},
	sidestar: {
		name: 'Sidestar',
		category: 'pisols',
		damageType: 'physical',
		damageType2: '',
		damage: 18,
		damage2: 0,
		ammoType: '.27 Caliber',
		magCapacity: 17,
		fireRate: 40,
		range: 20,
		accuracy: 67.9,
		mass: 0.65,
		value: 825,
		picture: 'Sidestar.webp',
		modSlots: [
			{
				slotType: 'barrel',
				mods: [
					//first mod slot should be the default mod
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'laser',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'optic',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'muzzle',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'grip and stock',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'magazine and battery',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'internal',
				mods: [
					{ name: 'No Mod', description: '' },
					{
						name: 'Hair Trigger',
						description:
							'installs a lighter trigger pull for increase fire rate',
					},
					{ name: 'High Powered', description: 'increases damage done' },
					{
						name: 'High Velocity',
						description: 'internal module that increases accuracy and range',
					},
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'receiver',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
		],
	},
	urbanEagle: {
		name: 'Urban Eagle',
		category: 'pistol',
		damageType: 'physical',
		damageType2: '',
		damage: 39,
		damage2: 0,
		ammoType: '.43 Ultramag',
		magCapacity: 8,
		fireRate: 25,
		range: 20,
		accuracy: 67.7,
		mass: 1.75,
		value: 4800,
		picture: 'Urban_Eagle.webp',
		modSlots: [
			{
				slotType: 'barrel',
				mods: [
					//first mod slot should be the default mod
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'laser',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'optic',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'muzzle',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'grip and stock',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'magazine and battery',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'internal',
				mods: [
					{ name: 'No Mod', description: '' },
					{
						name: 'Hair Trigger',
						description:
							'installs a lighter trigger pull for increase fire rate',
					},
					{ name: 'High Powered', description: 'increases damage done' },
					{
						name: 'High Velocity',
						description: 'internal module that increases accuracy and range',
					},
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'receiver',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
		],
	},
	xm2311: {
		name: 'XM-2311',
		category: 'pisols',
		damageType: 'physical',
		damageType2: '',
		damage: 36,
		damage2: 0,
		ammoType: '.45 Caliber',
		magCapacity: 9,
		fireRate: 67,
		range: 20,
		accuracy: 66.9,
		mass: 1.1,
		value: 8200,
		picture: 'XM-2311.webp',
		modSlots: [
			{
				slotType: 'barrel',
				mods: [
					//first mod slot should be the default mod
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'laser',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'optic',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'muzzle',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'grip and stock',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'magazine and battery',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'internal',
				mods: [
					{ name: 'No Mod', description: '' },
					{
						name: 'Hair Trigger',
						description:
							'installs a lighter trigger pull for increase fire rate',
					},
					{ name: 'High Powered', description: 'increases damage done' },
					{
						name: 'High Velocity',
						description: 'internal module that increases accuracy and range',
					},
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'receiver',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
		],
	},
}
