import { Weapon } from '@/utils/weaponType'

export const rifles: Record<string, Weapon> = {
	aa99: {
		name: 'AA-99',
		category: '',
		damageType: '',
		damageType2: '',
		damage: 0,
		damage2: 0,
		ammoType: '',
		magCapacity: 0,
		fireRate: 0,
		range: 0,
		accuracy: 0,
		mass: 0,
		value: 0,
		picture: 'AA-99.webp',
		modSlots: [
			{
				slotType: 'barrel',
				mods: [
					//first mod slot should be the default mod
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'laser',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'optic',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'muzzle',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'grip and stock',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'magazine and battery',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'internal',
				mods: [
					{ name: 'No Mod', description: '' },
					{
						name: 'Hair Trigger',
						description:
							'installs a lighter trigger pull for increase fire rate',
					},
					{ name: 'High Powered', description: 'increases damage done' },
					{
						name: 'High Velocity',
						description: 'internal module that increases accuracy and range',
					},
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'receiver',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
		],
	},
	beowulf: {
		name: 'Beowulf',
		category: '',
		damageType: '',
		damageType2: '',
		damage: 0,
		damage2: 0,
		ammoType: '',
		magCapacity: 0,
		fireRate: 0,
		range: 0,
		accuracy: 0,
		mass: 0,
		value: 0,
		picture: 'Beowulf.webp',
		modSlots: [
			{
				slotType: 'barrel',
				mods: [
					//first mod slot should be the default mod
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'laser',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'optic',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'muzzle',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'grip and stock',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'magazine and battery',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'internal',
				mods: [
					{ name: 'No Mod', description: '' },
					{
						name: 'Hair Trigger',
						description:
							'installs a lighter trigger pull for increase fire rate',
					},
					{ name: 'High Powered', description: 'increases damage done' },
					{
						name: 'High Velocity',
						description: 'internal module that increases accuracy and range',
					},
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'receiver',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
		],
	},
	drumBeat: {
		name: 'DrumBeat',
		category: '',
		damageType: '',
		damageType2: '',
		damage: 0,
		damage2: 0,
		ammoType: '',
		magCapacity: 0,
		fireRate: 0,
		range: 0,
		accuracy: 0,
		mass: 0,
		value: 0,
		picture: 'DrumBeat.webp',
		modSlots: [
			{
				slotType: 'barrel',
				mods: [
					//first mod slot should be the default mod
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'laser',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'optic',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'muzzle',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'grip and stock',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'magazine and battery',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'internal',
				mods: [
					{ name: 'No Mod', description: '' },
					{
						name: 'Hair Trigger',
						description:
							'installs a lighter trigger pull for increase fire rate',
					},
					{ name: 'High Powered', description: 'increases damage done' },
					{
						name: 'High Velocity',
						description: 'internal module that increases accuracy and range',
					},
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'receiver',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
		],
	},
	grendal: {
		name: 'Grendel',
		category: '',
		damageType: '',
		damageType2: '',
		damage: 0,
		damage2: 0,
		ammoType: '',
		magCapacity: 0,
		fireRate: 0,
		range: 0,
		accuracy: 0,
		mass: 0,
		value: 0,
		picture: 'Grendel.webp',
		modSlots: [
			{
				slotType: 'barrel',
				mods: [
					//first mod slot should be the default mod
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'laser',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'optic',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'muzzle',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'grip and stock',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'magazine and battery',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'internal',
				mods: [
					{ name: 'No Mod', description: '' },
					{
						name: 'Hair Trigger',
						description:
							'installs a lighter trigger pull for increase fire rate',
					},
					{ name: 'High Powered', description: 'increases damage done' },
					{
						name: 'High Velocity',
						description: 'internal module that increases accuracy and range',
					},
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'receiver',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
		],
	},
	kodama: {
		name: 'Kodama',
		category: '',
		damageType: '',
		damageType2: '',
		damage: 0,
		damage2: 0,
		ammoType: '',
		magCapacity: 0,
		fireRate: 0,
		range: 0,
		accuracy: 0,
		mass: 0,
		value: 0,
		picture: 'Kodama.webp',
		modSlots: [
			{
				slotType: 'barrel',
				mods: [
					//first mod slot should be the default mod
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'laser',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'optic',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'muzzle',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'grip and stock',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'magazine and battery',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'internal',
				mods: [
					{ name: 'No Mod', description: '' },
					{
						name: 'Hair Trigger',
						description:
							'installs a lighter trigger pull for increase fire rate',
					},
					{ name: 'High Powered', description: 'increases damage done' },
					{
						name: 'High Velocity',
						description: 'internal module that increases accuracy and range',
					},
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'receiver',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
		],
	},
	lawgiver: {
		name: 'Lawgiver',
		category: '',
		damageType: '',
		damageType2: '',
		damage: 0,
		damage2: 0,
		ammoType: '',
		magCapacity: 0,
		fireRate: 0,
		range: 0,
		accuracy: 0,
		mass: 0,
		value: 0,
		picture: 'Lawgiver.webp',
		modSlots: [
			{
				slotType: 'barrel',
				mods: [
					//first mod slot should be the default mod
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'laser',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'optic',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'muzzle',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'grip and stock',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'magazine and battery',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'internal',
				mods: [
					{ name: 'No Mod', description: '' },
					{
						name: 'Hair Trigger',
						description:
							'installs a lighter trigger pull for increase fire rate',
					},
					{ name: 'High Powered', description: 'increases damage done' },
					{
						name: 'High Velocity',
						description: 'internal module that increases accuracy and range',
					},
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'receiver',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
		],
	},
	maelstrom: {
		name: 'Maelstrom',
		category: '',
		damageType: '',
		damageType2: '',
		damage: 0,
		damage2: 0,
		ammoType: '',
		magCapacity: 0,
		fireRate: 0,
		range: 0,
		accuracy: 0,
		mass: 0,
		value: 0,
		picture: 'Maelstrom.webp',
		modSlots: [
			{
				slotType: 'barrel',
				mods: [
					//first mod slot should be the default mod
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'laser',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'optic',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'muzzle',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'grip and stock',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'magazine and battery',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'internal',
				mods: [
					{ name: 'No Mod', description: '' },
					{
						name: 'Hair Trigger',
						description:
							'installs a lighter trigger pull for increase fire rate',
					},
					{ name: 'High Powered', description: 'increases damage done' },
					{
						name: 'High Velocity',
						description: 'internal module that increases accuracy and range',
					},
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'receiver',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
		],
	},
	magpulse: {
		name: 'Magpulse',
		category: '',
		damageType: '',
		damageType2: '',
		damage: 0,
		damage2: 0,
		ammoType: '',
		magCapacity: 0,
		fireRate: 0,
		range: 0,
		accuracy: 0,
		mass: 0,
		value: 0,
		picture: 'Magpulse.webp',
		modSlots: [
			{
				slotType: 'barrel',
				mods: [
					//first mod slot should be the default mod
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'laser',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'optic',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'muzzle',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'grip and stock',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'magazine and battery',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'internal',
				mods: [
					{ name: 'No Mod', description: '' },
					{
						name: 'Hair Trigger',
						description:
							'installs a lighter trigger pull for increase fire rate',
					},
					{ name: 'High Powered', description: 'increases damage done' },
					{
						name: 'High Velocity',
						description: 'internal module that increases accuracy and range',
					},
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'receiver',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
		],
	},
	magshear: {
		name: 'Magshear',
		category: '',
		damageType: '',
		damageType2: '',
		damage: 0,
		damage2: 0,
		ammoType: '',
		magCapacity: 0,
		fireRate: 0,
		range: 0,
		accuracy: 0,
		mass: 0,
		value: 0,
		picture: 'Magshear.webp',
		modSlots: [
			{
				slotType: 'barrel',
				mods: [
					//first mod slot should be the default mod
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'laser',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'optic',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'muzzle',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'grip and stock',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'magazine and battery',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'internal',
				mods: [
					{ name: 'No Mod', description: '' },
					{
						name: 'Hair Trigger',
						description:
							'installs a lighter trigger pull for increase fire rate',
					},
					{ name: 'High Powered', description: 'increases damage done' },
					{
						name: 'High Velocity',
						description: 'internal module that increases accuracy and range',
					},
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'receiver',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
		],
	},
	magsniper: {
		name: 'Magsniper',
		category: '',
		damageType: '',
		damageType2: '',
		damage: 0,
		damage2: 0,
		ammoType: '',
		magCapacity: 0,
		fireRate: 0,
		range: 0,
		accuracy: 0,
		mass: 0,
		value: 0,
		picture: 'Magsniper.webp',
		modSlots: [
			{
				slotType: 'barrel',
				mods: [
					//first mod slot should be the default mod
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'laser',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'optic',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'muzzle',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'grip and stock',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'magazine and battery',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'internal',
				mods: [
					{ name: 'No Mod', description: '' },
					{
						name: 'Hair Trigger',
						description:
							'installs a lighter trigger pull for increase fire rate',
					},
					{ name: 'High Powered', description: 'increases damage done' },
					{
						name: 'High Velocity',
						description: 'internal module that increases accuracy and range',
					},
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'receiver',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
		],
	},
	oldAssaultRifle: {
		name: 'Old Earth Assault Rifle',
		category: '',
		damageType: '',
		damageType2: '',
		damage: 0,
		damage2: 0,
		ammoType: '',
		magCapacity: 0,
		fireRate: 0,
		range: 0,
		accuracy: 0,
		mass: 0,
		value: 0,
		picture: 'Old_Earth_Assault_Rifle.webp',
		modSlots: [
			{
				slotType: 'barrel',
				mods: [
					//first mod slot should be the default mod
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'laser',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'optic',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'muzzle',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'grip and stock',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'magazine and battery',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'internal',
				mods: [
					{ name: 'No Mod', description: '' },
					{
						name: 'Hair Trigger',
						description:
							'installs a lighter trigger pull for increase fire rate',
					},
					{ name: 'High Powered', description: 'increases damage done' },
					{
						name: 'High Velocity',
						description: 'internal module that increases accuracy and range',
					},
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'receiver',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
		],
	},
	oldHuntingRifle: {
		name: 'Old Earth Hunting Rifle',
		category: '',
		damageType: '',
		damageType2: '',
		damage: 0,
		damage2: 0,
		ammoType: '',
		magCapacity: 0,
		fireRate: 0,
		range: 0,
		accuracy: 0,
		mass: 0,
		value: 0,
		picture: 'Old_Earth_Hunting_Rifle.webp',
		modSlots: [
			{
				slotType: 'barrel',
				mods: [
					//first mod slot should be the default mod
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'laser',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'optic',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'muzzle',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'grip and stock',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'magazine and battery',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'internal',
				mods: [
					{ name: 'No Mod', description: '' },
					{
						name: 'Hair Trigger',
						description:
							'installs a lighter trigger pull for increase fire rate',
					},
					{ name: 'High Powered', description: 'increases damage done' },
					{
						name: 'High Velocity',
						description: 'internal module that increases accuracy and range',
					},
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'receiver',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
		],
	},
	tombstone: {
		name: 'Tombstone',
		category: '',
		damageType: '',
		damageType2: '',
		damage: 0,
		damage2: 0,
		ammoType: '',
		magCapacity: 0,
		fireRate: 0,
		range: 0,
		accuracy: 0,
		mass: 0,
		value: 0,
		picture: 'Tombstone.webp',
		modSlots: [
			{
				slotType: 'barrel',
				mods: [
					//first mod slot should be the default mod
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'laser',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'optic',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'muzzle',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'grip and stock',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'magazine and battery',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'internal',
				mods: [
					{ name: 'No Mod', description: '' },
					{
						name: 'Hair Trigger',
						description:
							'installs a lighter trigger pull for increase fire rate',
					},
					{ name: 'High Powered', description: 'increases damage done' },
					{
						name: 'High Velocity',
						description: 'internal module that increases accuracy and range',
					},
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'receiver',
				mods: [
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
					{ name: '', description: '' },
				],
				defaultMod: 0,
				disabled: false,
			},
		],
	},
}

/* Weapon Template

nameInCamelCase: {
		name: '',
		category: '',
		damageType: '',
    damageType2: '',
		damage: 0,
    damage2: 0,
    ammoType: '',
    magCapacity: 0,
    fireRate: 0,
    range: 0,
    accuracy: 0,
		mass: 0,
		value: 0,
		modSlots: [
			{
				slotType: 'barrel',
				mods: [ //first mod slot should be the default mod
					{ name: '', description: '' },
					{ name: '', description: '', },
					{ name: '', description: '', },
					{ name: '', description: '', },
					{ name: '', description: '', },
					{ name: '', description: '', },
				],
				defaultMod: 0,
				disabled: false,
			},
			{
				slotType: 'laser',
				mods: [
					{ name: '', description: '', },
					{ name: '', description: '', },
					{ name: '', description: '', },
					{ name: '', description: '', },
					{ name: '', description: '', },
					{ name: '', description: '', },
					{ name: '', description: '', },
				],
				defaultMod: 0,
				disabled: false,
			},
      {
				slotType: 'optic',
				mods: [
					{ name: '', description: '', },
					{ name: '', description: '', },
					{ name: '', description: '', },
					{ name: '', description: '', },
					{ name: '', description: '', },
					{ name: '', description: '', },
					{ name: '', description: '', },
				],
				defaultMod: 0,
				disabled: false,
			},
      {
				slotType: 'muzzle',
				mods: [
					{ name: '', description: '', },
					{ name: '', description: '', },
					{ name: '', description: '', },
					{ name: '', description: '', },
					{ name: '', description: '', },
					{ name: '', description: '', },
					{ name: '', description: '', },
				],
				defaultMod: 0,
				disabled: false,
			},
      {
				slotType: 'grip and stock',
				mods: [
					{ name: '', description: '', },
					{ name: '', description: '', },
					{ name: '', description: '', },
					{ name: '', description: '', },
					{ name: '', description: '', },
					{ name: '', description: '', },
					{ name: '', description: '', },
				],
				defaultMod: 0,
				disabled: false,
			},
      {
				slotType: 'magazine and battery',
				mods: [
					{ name: '', description: '', },
					{ name: '', description: '', },
					{ name: '', description: '', },
					{ name: '', description: '', },
					{ name: '', description: '', },
					{ name: '', description: '', },
					{ name: '', description: '', },
				],
				defaultMod: 0,
				disabled: false,
			},
      {
				slotType: 'internal',
				mods: [
					{ name: 'No Mod', description: '', },
					{ name: 'Hair Trigger', description: 'installs a lighter trigger pull for increase fire rate', },
					{ name: 'High Powered', description: 'increases damage done', },
					{ name: 'High Velocity', description: 'internal module that increases accuracy and range', },
				],
				defaultMod: 0,
				disabled: false,
			},
      {
				slotType: 'receiver',
				mods: [
					{ name: '', description: '', },
					{ name: '', description: '', },
					{ name: '', description: '', },
					{ name: '', description: '', },
					{ name: '', description: '', },
					{ name: '', description: '', },
					{ name: '', description: '', },
				],
				defaultMod: 0,
				disabled: false,
			},
		],
	},

*/
